import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');

const additions = {
  ja: {
    'meta.description':'外国人向けSIMサービスSUMOU sim。月額880円から、コンビニ払い、多言語サポート、全国送料無料に対応。日本に来る前から申し込みできます。',
    'a11y.skip':'本文へ移動','a11y.language':'言語を選択','common.sourceDate':'情報確認日：','common.yes':'あり','common.no':'なし','common.free':'無料',
    'plan.summary.call':'電話番号・通話・SMS・データが使えるプラン','plan.summary.data':'データ通信とSMSに絞ったプラン','plan.perMonth':'/月','plan.taxIncluded':'税込','plan.call.features':'電話番号・通話・SMS・データ','plan.data.features':'データ・SMS',
    'plan.call-light.name':'ライト','plan.call-light.data':'1GB','plan.call-basic.name':'ベーシック','plan.call-basic.data':'3GB','plan.call-standard.name':'スタンダード','plan.call-standard.data':'20GB','plan.call-max.name':'SUMOU MAX','plan.call-max.data':'直近3日で10GB','plan.data-basic.name':'ベーシック','plan.data-basic.data':'3GB','plan.data-standard.name':'スタンダード','plan.data-standard.data':'20GB','plan.data-max.name':'SUMOU MAX','plan.data-max.data':'直近3日で10GB',
    'note.pricing':'表示価格は税込です。契約事務手数料3,300円が初回のみ必要です。通話料、SMS送信料、追加データなどは別料金です。料金・キャンペーンは変更される場合があります。申込ページで最新条件をご確認ください。','note.maxPlan':'SUMOU MAXはデータ繰越・追加チャージの対象外です。','note.speed':'通信速度は技術規格上の最大値です。実際の速度は場所、時間帯、端末、混雑状況などにより変わります。','note.identity':'本人確認の方法は申込区分や受取方法によって異なります。申込ページに表示される最新の案内を確認してください。','note.device':'ご利用前に、端末の対応周波数・SIMロック・eSIM対応状況をご確認ください。','note.publication':'料金・条件は変更される場合があります。申込ページで最新情報をご確認ください。',
    'comparison.caption':'CALL SIMとDATA SIMの機能比較','comparison.item':'項目','comparison.data':'データ通信','comparison.phoneNumber':'日本の電話番号','comparison.voice':'音声通話','comparison.recommended':'おすすめ','comparison.callFor':'仕事・生活・各種手続き','comparison.dataFor':'通信専用・サブ端末',
    'network.dataTitle':'通信','network.carrierLabel':'回線','network.carrier':'NTTドコモ回線','network.standardLabel':'規格','network.standards':'4G/LTE、対応端末では5G','network.speedLabel':'参考\n最大速度','network.referenceMaxSpeed':'LTEベストエフォート\n下り最大375Mbps','network.limitLabel':'容量超過後','network.afterAllowance':'最大128kbps','network.callTitle':'通話','network.domesticCallLabel':'国内発信','network.domesticCall':'22円 / 30秒','network.incomingLabel':'国内着信','network.internationalLabel':'国際電話','network.unavailable':'利用不可','network.smsTitle':'SMS・データ追加','network.smsReceiveLabel':'SMS受信','network.smsDomesticLabel':'国内SMS送信','network.smsDomestic':'3.3円 / 通','network.smsInternationalLabel':'海外SMS送信','network.smsInternational':'110円 / 通','network.dataAddOnLabel':'データ追加','network.dataAddOn':'1GB 880円',
    'payment.convenience':'コンビニ払い','payment.credit':'クレジットカード','payment.bank':'口座振替','payment.cod':'代金引換','payment.codNote':'日本国内から申し込むCALL SIMの初期費用のみ',
    'identity.domestic.title':'日本国内からCALL SIM','identity.domestic.body':'オンライン申込後、セブン銀行ATMで在留カードを使った本人確認、または配送時の本人確認が必要になる場合があります。選択した申込方法の案内に従ってください。','identity.overseas.title':'海外からCALL SIM','identity.overseas.body':'パスポートを使って申し込み、羽田空港または成田空港でSIMカード、またはeSIMのアクティベーション情報を受け取る方法があります。','identity.data.body':'パスポートまたは在留カードの画像を申込時にアップロードします。',
    'steps.1.title':'プランを選ぶ','steps.1.body':'CALL SIMかDATA SIM、容量を選びます。','steps.2.title':'オンラインで申し込む','steps.2.body':'提携先申込ページに必要情報を入力します。','steps.3.title':'支払い・本人確認','steps.3.body':'案内に沿って初期費用の支払いと本人確認を行います。','steps.4.title':'SIM / eSIMを受け取る','steps.4.body':'配送、空港受取、メール案内など選択した方法で受け取ります。','steps.5.title':'初期設定して利用開始','steps.5.body':'APNまたはeSIMを設定して利用を始めます。',
    'faq.1.q':'外国人でも申し込めますか？','faq.1.a':'はい。必要な本人確認書類を用意し、オンラインで申し込めます。','faq.2.q':'海外から申し込めますか？','faq.2.a':'はい。海外から申し込み、日本到着後に空港で受け取る方法があります。プランと受取方法により手続きが異なります。','faq.3.q':'どの本人確認書類が必要ですか？','faq.3.a':'日本国内からCALL SIMを申し込む場合は主に在留カード、海外からの場合はパスポートが必要です。DATA SIMはパスポートまたは在留カードを使用できます。','faq.4.q':'クレジットカードがなくても申し込めますか？','faq.4.a':'はい。日本国内ではコンビニ払い、口座振替などを選べます。海外申込の初期費用はクレジットカードが必要となる場合があります。','faq.5.q':'eSIMは利用できますか？','faq.5.a':'対応しています。端末のeSIM対応状況と、プランごとの本人確認・受取条件をご確認ください。','faq.6.q':'日本の電話番号はもらえますか？','faq.6.a':'CALL SIMでは日本の電話番号を利用できます。DATA SIMは音声通話用の電話番号を提供しません。','faq.7.q':'今の電話番号を引き継げますか？','faq.7.a':'CALL SIMではMNPに対応しています。必要情報や期限があるため、申込ページの案内をご確認ください。','faq.8.q':'データを使い切るとどうなりますか？','faq.8.a':'最大128kbpsに速度制限されます。対象プランでは1GB 880円で追加できます。','faq.9.q':'最低利用期間や解約金はありますか？','faq.9.a':'最低利用期間はありません。公式サイトでは解約事務手数料無料キャンペーンが案内されています。恒久条件かを申込時に確認してください。','faq.10.q':'SIMカードはいつ届きますか？','faq.10.a':'支払いと審査が午後2時までに完了すると最短当日発送の案内があります。地域、在庫、審査状況などで変わります。','faq.11.q':'対応端末はどう確認しますか？','faq.11.a':'SIMロック、ドコモ回線の周波数、eSIM対応状況を端末メーカーや購入店で確認してください。',
    'footer.sellerPending':'販売主体・会社情報：公開前確認中','footer.relationshipPending':'SUMOU simとの契約関係および掲載許諾の確認後に表示します。','footer.preview':'公開前確認用LP',
    'image.hero':'日本人と外国人がスマートフォンを見ながら談笑している','image.payment':'コンビニのレジでスマートフォンを使って支払う様子','image.support':'ヘッドセットで案内するサポートスタッフ','image.setup':'届いたSIMカードを確認する利用者','image.overseas':'空港でスマートフォンを確認する旅行者'
  },
  en: {
    'meta.description':'SUMOU sim is a SIM service for international residents in Japan, with plans from ¥880/month, convenience-store payments, multilingual support, free delivery across Japan, and applications before arrival.','a11y.skip':'Skip to main content','a11y.language':'Select language',
    'feature.phone.title':'Japanese phone number','feature.phone.body':'With CALL SIM, you get a Japanese phone number for work and everyday life.','feature.overseas.title':'Apply from overseas','feature.overseas.body':'Apply before you arrive so you can aim to get connected soon after landing.','feature.payment.title':'Flexible payment options','feature.payment.body':'Pay at convenience stores, by credit card, bank transfer, and more.','feature.support.title':'Multilingual support','feature.support.body':'Support is primarily available in Japanese, English, Chinese, and Vietnamese.','feature.delivery.title':'Free nationwide delivery','feature.delivery.body':'Physical SIM cards are delivered free of charge within Japan.','feature.5g.title':'5G ready','feature.5g.body':'On a compatible device, you can switch to 5G after activation at no extra charge.',
    'problem.1':'Contracts in Japanese are difficult','problem.2':'I do not have a credit card','problem.3':'I do not know which plan suits me','problem.4':'I need a Japanese phone number','problem.5':'I do not understand identity verification','problem.6':'I want to prepare before arriving in Japan','problem.answer':'With SUMOU sim, you can review the essential information clearly and apply online.',
    'reasons.title':'Why choose SUMOU sim','reasons.lead':'Clear guidance on everything you need, from application to activation.','reasons.payment.title':'Choose how you pay','reasons.payment.body':'Even without a credit card, you can choose convenience-store payment, bank transfer, and other options.','reasons.support.title':'Multilingual assistance','reasons.support.body':'Support is primarily available in Japanese, English, Chinese, and Vietnamese.','reasons.setup.title':'Start with your chosen delivery method','reasons.setup.body':'Receive your service by delivery, airport pickup, or email instructions, depending on your selection.',
    'plan.summary.call':'A plan with a phone number, voice calls, SMS, and data','plan.summary.data':'A plan focused on data and SMS','plan.perMonth':'/mo.','plan.taxIncluded':'Tax included','plan.call.features':'Phone number, calls, SMS, and data','plan.data.features':'Data and SMS','plan.call-light.name':'Light','plan.call-light.data':'1GB','plan.call-basic.name':'Basic','plan.call-basic.data':'3GB','plan.call-standard.name':'Standard','plan.call-standard.data':'20GB','plan.call-max.name':'SUMOU MAX','plan.call-max.data':'10GB in the most recent 3 days','plan.data-basic.name':'Basic','plan.data-basic.data':'3GB','plan.data-standard.name':'Standard','plan.data-standard.data':'20GB','plan.data-max.name':'SUMOU MAX','plan.data-max.data':'10GB in the most recent 3 days',
    'note.pricing':'Prices include tax. A one-time contract administration fee of ¥3,300 is charged initially. Calls, outgoing SMS, extra data, and other services cost extra. Prices and promotions may change; check the application page for the latest terms.','note.maxPlan':'SUMOU MAX is not eligible for data rollover or additional data purchases.','note.speed':'The stated speed is the technical maximum. Actual speeds vary by location, time, device, network congestion, and other factors.','note.identity':'Identity verification varies by application category and delivery method. Follow the latest instructions shown on the application page.','note.device':'Before use, confirm the device’s supported frequencies, SIM-lock status, and eSIM compatibility.','note.publication':'Prices and conditions may change. Check the application page for the latest information.',
    'common.sourceDate':'Information checked: ','common.yes':'Yes','common.no':'No','common.free':'Free',
    'comparison.title':'CALL SIM vs. DATA SIM','comparison.caption':'Feature comparison of CALL SIM and DATA SIM','comparison.item':'Feature','comparison.data':'Mobile data','comparison.phoneNumber':'Japanese phone number','comparison.voice':'Voice calls','comparison.recommended':'Best for','comparison.callFor':'Work, daily life, and official procedures','comparison.dataFor':'Data-only use and secondary devices',
    'network.title':'Network, speed, calls, and SMS','network.lead':'Key network conditions and additional charges to know before you start.','network.dataTitle':'Data service','network.carrierLabel':'Network','network.carrier':'NTT DOCOMO network','network.standardLabel':'Technology','network.standards':'4G/LTE; 5G on compatible devices','network.speedLabel':'Reference maximum speed','network.referenceMaxSpeed':'LTE best effort: up to 375Mbps download','network.limitLabel':'After data allowance','network.afterAllowance':'Up to 128kbps','network.callTitle':'Calls','network.domesticCallLabel':'Domestic outgoing calls','network.domesticCall':'¥22 / 30 sec.','network.incomingLabel':'Domestic incoming calls','network.internationalLabel':'International calls','network.unavailable':'Not available','network.smsTitle':'SMS and extra data','network.smsReceiveLabel':'Incoming SMS','network.smsDomesticLabel':'Domestic outgoing SMS','network.smsDomestic':'¥3.3 / message','network.smsInternationalLabel':'International outgoing SMS','network.smsInternational':'¥110 / message','network.dataAddOnLabel':'Extra data','network.dataAddOn':'1GB for ¥880',
    'payment.title':'Apply even without a credit card.','payment.convenience':'Convenience-store payment','payment.credit':'Credit card','payment.bank':'Bank account transfer','payment.cod':'Cash on delivery','payment.codNote':'Initial fees for CALL SIM applications made within Japan only','payment.note':'Billing dates and cancellation deadlines vary by payment method. Check the application page and terms of service for details.',
    'identity.title':'Check how identity verification works.','identity.domestic.title':'CALL SIM application from Japan','identity.domestic.body':'After applying online, you may need to verify your identity at a Seven Bank ATM using your residence card, or complete identity verification at delivery. Follow the instructions for the application method you selected.','identity.overseas.title':'CALL SIM application from overseas','identity.overseas.body':'Apply using your passport, then receive the physical SIM or eSIM activation information at Haneda or Narita Airport.','identity.data.body':'Upload an image of your passport or residence card during the application.','steps.1.title':'Choose a plan','steps.1.body':'Choose CALL SIM or DATA SIM and your data allowance.','steps.2.title':'Apply online','steps.2.body':'Enter the required information on the partner application page.','steps.3.title':'Pay and verify your identity','steps.3.body':'Follow the instructions to pay the initial fees and complete identity verification.','steps.4.title':'Receive your SIM or eSIM','steps.4.body':'Receive it by delivery, airport pickup, or email instructions, depending on your selection.','steps.5.title':'Set up and connect','steps.5.body':'Configure the APN or eSIM and start using the service.',
    'overseas.body':'Apply from overseas and receive your physical SIM or eSIM instructions at the airport after arriving in Japan. Depending on the conditions, DATA eSIM instructions may be completed entirely online.','overseas.note':'Because CALL eSIM requires legally mandated identity verification, the process may not be completed by email alone; document pickup at an airport or another location may be required.','device.title':'Compatible devices and eSIM','device.body':'Use a SIM-free device, a SIM-unlocked device, or a device compatible with the DOCOMO network. If you choose eSIM, also confirm that your device supports eSIM.','final.body':'Choose the plan that suits you and apply online.',
    'faq.1.q':'Can foreign nationals apply?','faq.1.a':'Yes. Prepare the required identity documents and apply online.','faq.2.q':'Can I apply from outside Japan?','faq.2.a':'Yes. You can apply from overseas and pick up your service at an airport after arriving in Japan. Procedures vary by plan and pickup method.','faq.3.q':'Which identity documents do I need?','faq.3.a':'For a CALL SIM application from Japan, you generally need a residence card; from overseas, you need a passport. For DATA SIM, you can use a passport or residence card.','faq.4.q':'Can I apply without a credit card?','faq.4.a':'Yes. Within Japan, you can choose convenience-store payment, bank transfer, and other methods. A credit card may be required for initial fees when applying from overseas.','faq.5.q':'Can I use eSIM?','faq.5.a':'Yes. Confirm your device’s eSIM compatibility and the identity-verification and pickup requirements for your plan.','faq.6.q':'Will I get a Japanese phone number?','faq.6.a':'CALL SIM includes a Japanese phone number. DATA SIM does not provide a number for voice calls.','faq.7.q':'Can I keep my current phone number?','faq.7.a':'CALL SIM supports mobile number portability (MNP). Check the application page because required information and deadlines apply.','faq.8.q':'What happens when I use all my data?','faq.8.a':'Your speed is limited to a maximum of 128kbps. Eligible plans can add 1GB for ¥880.','faq.9.q':'Is there a minimum term or cancellation fee?','faq.9.a':'There is no minimum term. The official site currently advertises a campaign waiving the cancellation administration fee. Confirm at application whether this is a permanent condition.','faq.10.q':'When will my SIM card arrive?','faq.10.a':'The service states that orders may ship the same day when payment and screening are completed by 2:00 p.m. Delivery varies by area, stock, and screening status.','faq.11.q':'How do I check device compatibility?','faq.11.a':'Check the SIM-lock status, DOCOMO network frequency support, and eSIM compatibility with the manufacturer or retailer.',
    'footer.sellerPending':'Seller and company information: pending pre-publication verification','footer.relationshipPending':'This information will be displayed after the relationship with SUMOU sim and publication permission are confirmed.','footer.preview':'Pre-publication preview page','image.hero':'A Japanese adult and an international resident smiling together while looking at a smartphone','image.payment':'A customer paying with a smartphone at a convenience-store register','image.support':'A support representative assisting a customer while wearing a headset','image.setup':'A customer checking a newly delivered SIM card','image.overseas':'A traveler checking a smartphone at an airport'
  },
  vi: {
    'meta.description':'SUMOU sim là dịch vụ SIM dành cho người nước ngoài tại Nhật Bản, với gói cước từ 880 yên/tháng, thanh toán tại cửa hàng tiện lợi, hỗ trợ đa ngôn ngữ, giao hàng miễn phí toàn quốc và đăng ký trước khi đến Nhật.','a11y.skip':'Chuyển đến nội dung chính','a11y.language':'Chọn ngôn ngữ',
    'feature.phone.title':'Số điện thoại Nhật Bản','feature.phone.body':'Với CALL SIM, bạn có số điện thoại Nhật Bản để dùng cho công việc và cuộc sống hằng ngày.','feature.overseas.title':'Đăng ký từ nước ngoài','feature.overseas.body':'Đăng ký trước khi đến Nhật để có thể bắt đầu kết nối sớm sau khi nhập cảnh.','feature.payment.title':'Nhiều phương thức thanh toán','feature.payment.body':'Hỗ trợ thanh toán tại cửa hàng tiện lợi, thẻ tín dụng, trích nợ tài khoản và nhiều hình thức khác.','feature.support.title':'Hỗ trợ đa ngôn ngữ','feature.support.body':'Hỗ trợ chủ yếu bằng tiếng Nhật, tiếng Anh, tiếng Trung và tiếng Việt.','feature.delivery.title':'Miễn phí giao hàng toàn quốc','feature.delivery.body':'SIM vật lý được giao miễn phí trong phạm vi Nhật Bản.','feature.5g.title':'Hỗ trợ 5G','feature.5g.body':'Với thiết bị tương thích, bạn có thể chuyển sang 5G sau khi kích hoạt mà không mất thêm phí.',
    'problem.1':'Hợp đồng bằng tiếng Nhật khó hiểu','problem.2':'Tôi không có thẻ tín dụng','problem.3':'Tôi không biết gói nào phù hợp','problem.4':'Tôi cần số điện thoại Nhật Bản','problem.5':'Tôi chưa rõ cách xác minh danh tính','problem.6':'Tôi muốn chuẩn bị trước khi đến Nhật','problem.answer':'Với SUMOU sim, bạn có thể xem rõ những thông tin cần thiết và đăng ký trực tuyến.',
    'reasons.title':'Vì sao nên chọn SUMOU sim','reasons.lead':'Hướng dẫn rõ ràng mọi điều cần biết, từ đăng ký đến khi bắt đầu sử dụng.','reasons.payment.title':'Tự chọn cách thanh toán','reasons.payment.body':'Ngay cả khi không có thẻ tín dụng, bạn vẫn có thể chọn thanh toán tại cửa hàng tiện lợi, trích nợ tài khoản và các phương thức khác.','reasons.support.title':'Hỗ trợ đa ngôn ngữ','reasons.support.body':'Hỗ trợ chủ yếu bằng tiếng Nhật, tiếng Anh, tiếng Trung và tiếng Việt.','reasons.setup.title':'Bắt đầu theo cách nhận đã chọn','reasons.setup.body':'Nhận dịch vụ qua giao hàng, tại sân bay hoặc hướng dẫn qua email, tùy theo lựa chọn của bạn.',
    'plan.summary.call':'Gói có số điện thoại, gọi thoại, SMS và dữ liệu','plan.summary.data':'Gói tập trung vào dữ liệu và SMS','plan.perMonth':'/tháng','plan.taxIncluded':'Đã gồm thuế','plan.call.features':'Số điện thoại, gọi thoại, SMS và dữ liệu','plan.data.features':'Dữ liệu và SMS','plan.call-light.name':'Gói Nhẹ','plan.call-light.data':'1GB','plan.call-basic.name':'Gói Cơ bản','plan.call-basic.data':'3GB','plan.call-standard.name':'Gói Tiêu chuẩn','plan.call-standard.data':'20GB','plan.call-max.name':'SUMOU MAX','plan.call-max.data':'10GB trong 3 ngày gần nhất','plan.data-basic.name':'Gói Cơ bản','plan.data-basic.data':'3GB','plan.data-standard.name':'Gói Tiêu chuẩn','plan.data-standard.data':'20GB','plan.data-max.name':'SUMOU MAX','plan.data-max.data':'10GB trong 3 ngày gần nhất',
    'note.pricing':'Giá hiển thị đã bao gồm thuế. Phí thủ tục hợp đồng 3.300 yên chỉ thu một lần khi bắt đầu. Phí gọi, gửi SMS, mua thêm dữ liệu và các dịch vụ khác được tính riêng. Giá và chương trình khuyến mãi có thể thay đổi; vui lòng kiểm tra điều kiện mới nhất trên trang đăng ký.','note.maxPlan':'SUMOU MAX không áp dụng chuyển tiếp dữ liệu hoặc mua thêm dữ liệu.','note.speed':'Tốc độ nêu trên là mức tối đa theo thông số kỹ thuật. Tốc độ thực tế thay đổi tùy địa điểm, thời gian, thiết bị, mức độ nghẽn mạng và các yếu tố khác.','note.identity':'Cách xác minh danh tính khác nhau tùy hình thức đăng ký và cách nhận. Hãy làm theo hướng dẫn mới nhất trên trang đăng ký.','note.device':'Trước khi sử dụng, hãy kiểm tra băng tần hỗ trợ, tình trạng khóa SIM và khả năng tương thích eSIM của thiết bị.','note.publication':'Giá và điều kiện có thể thay đổi. Vui lòng kiểm tra thông tin mới nhất trên trang đăng ký.',
    'common.sourceDate':'Ngày kiểm tra thông tin: ','common.yes':'Có','common.no':'Không','common.free':'Miễn phí',
    'comparison.title':'So sánh CALL SIM và DATA SIM','comparison.caption':'Bảng so sánh tính năng CALL SIM và DATA SIM','comparison.item':'Hạng mục','comparison.data':'Dữ liệu di động','comparison.phoneNumber':'Số điện thoại Nhật Bản','comparison.voice':'Gọi thoại','comparison.recommended':'Phù hợp với','comparison.callFor':'Công việc, đời sống và các thủ tục','comparison.dataFor':'Chỉ dùng dữ liệu và thiết bị phụ',
    'network.title':'Mạng, tốc độ, cuộc gọi và SMS','network.lead':'Các điều kiện mạng và chi phí bổ sung cần biết trước khi sử dụng.','network.dataTitle':'Dữ liệu','network.carrierLabel':'Mạng','network.carrier':'Mạng NTT DOCOMO','network.standardLabel':'Công nghệ','network.standards':'4G/LTE; 5G trên thiết bị tương thích','network.speedLabel':'Tốc độ tối đa tham khảo','network.referenceMaxSpeed':'LTE best effort: tải xuống tối đa 375Mbps','network.limitLabel':'Sau khi hết dung lượng','network.afterAllowance':'Tối đa 128kbps','network.callTitle':'Cuộc gọi','network.domesticCallLabel':'Gọi đi trong nước','network.domesticCall':'22 yên / 30 giây','network.incomingLabel':'Nhận cuộc gọi trong nước','network.internationalLabel':'Gọi quốc tế','network.unavailable':'Không khả dụng','network.smsTitle':'SMS và dữ liệu bổ sung','network.smsReceiveLabel':'Nhận SMS','network.smsDomesticLabel':'Gửi SMS trong nước','network.smsDomestic':'3,3 yên / tin','network.smsInternationalLabel':'Gửi SMS quốc tế','network.smsInternational':'110 yên / tin','network.dataAddOnLabel':'Mua thêm dữ liệu','network.dataAddOn':'1GB với giá 880 yên',
    'payment.title':'Không có thẻ tín dụng vẫn có thể đăng ký.','payment.convenience':'Thanh toán tại cửa hàng tiện lợi','payment.credit':'Thẻ tín dụng','payment.bank':'Trích nợ tài khoản ngân hàng','payment.cod':'Thanh toán khi nhận hàng','payment.codNote':'Chỉ áp dụng cho phí ban đầu của CALL SIM đăng ký tại Nhật Bản','payment.note':'Ngày thanh toán và hạn làm thủ tục hủy khác nhau tùy phương thức thanh toán. Vui lòng xem trang đăng ký và điều khoản sử dụng để biết chi tiết.',
    'identity.title':'Hãy kiểm tra cách xác minh danh tính.','identity.domestic.title':'Đăng ký CALL SIM từ Nhật Bản','identity.domestic.body':'Sau khi đăng ký trực tuyến, bạn có thể cần xác minh danh tính tại ATM Seven Bank bằng thẻ cư trú hoặc xác minh khi nhận hàng. Hãy làm theo hướng dẫn của phương thức đăng ký đã chọn.','identity.overseas.title':'Đăng ký CALL SIM từ nước ngoài','identity.overseas.body':'Đăng ký bằng hộ chiếu, sau đó nhận SIM vật lý hoặc thông tin kích hoạt eSIM tại sân bay Haneda hoặc Narita.','identity.data.body':'Tải ảnh hộ chiếu hoặc thẻ cư trú lên khi đăng ký.','steps.1.title':'Chọn gói cước','steps.1.body':'Chọn CALL SIM hoặc DATA SIM và dung lượng dữ liệu.','steps.2.title':'Đăng ký trực tuyến','steps.2.body':'Nhập thông tin cần thiết trên trang đăng ký của đối tác.','steps.3.title':'Thanh toán và xác minh danh tính','steps.3.body':'Làm theo hướng dẫn để thanh toán phí ban đầu và hoàn tất xác minh danh tính.','steps.4.title':'Nhận SIM hoặc eSIM','steps.4.body':'Nhận qua giao hàng, tại sân bay hoặc hướng dẫn qua email, tùy theo lựa chọn của bạn.','steps.5.title':'Cài đặt và bắt đầu sử dụng','steps.5.body':'Cài đặt APN hoặc eSIM rồi bắt đầu sử dụng dịch vụ.',
    'overseas.body':'Đăng ký từ nước ngoài và nhận SIM vật lý hoặc hướng dẫn eSIM tại sân bay sau khi đến Nhật. Tùy điều kiện, hướng dẫn DATA eSIM có thể được hoàn tất hoàn toàn trực tuyến.','overseas.note':'Do CALL eSIM phải xác minh danh tính theo quy định pháp luật, thủ tục có thể không hoàn tất chỉ qua email; bạn có thể phải nhận giấy tờ tại sân bay hoặc địa điểm khác.','device.title':'Thiết bị tương thích và eSIM','device.body':'Có thể sử dụng thiết bị SIM-free, thiết bị đã mở khóa SIM hoặc thiết bị tương thích với mạng DOCOMO. Nếu chọn eSIM, hãy kiểm tra thiết bị có hỗ trợ eSIM hay không.','final.body':'Chọn gói phù hợp với bạn và đăng ký trực tuyến.',
    'faq.1.q':'Người nước ngoài có thể đăng ký không?','faq.1.a':'Có. Hãy chuẩn bị giấy tờ xác minh danh tính cần thiết và đăng ký trực tuyến.','faq.2.q':'Tôi có thể đăng ký từ nước ngoài không?','faq.2.a':'Có. Bạn có thể đăng ký từ nước ngoài và nhận dịch vụ tại sân bay sau khi đến Nhật. Thủ tục khác nhau tùy gói và cách nhận.','faq.3.q':'Tôi cần giấy tờ xác minh danh tính nào?','faq.3.a':'Khi đăng ký CALL SIM từ Nhật Bản, thông thường cần thẻ cư trú; khi đăng ký từ nước ngoài cần hộ chiếu. DATA SIM có thể dùng hộ chiếu hoặc thẻ cư trú.','faq.4.q':'Không có thẻ tín dụng có đăng ký được không?','faq.4.a':'Có. Tại Nhật Bản, bạn có thể chọn thanh toán tại cửa hàng tiện lợi, trích nợ tài khoản và các phương thức khác. Phí ban đầu khi đăng ký từ nước ngoài có thể yêu cầu thẻ tín dụng.','faq.5.q':'Có thể dùng eSIM không?','faq.5.a':'Có. Hãy kiểm tra thiết bị hỗ trợ eSIM và các điều kiện xác minh danh tính, nhận dịch vụ của từng gói.','faq.6.q':'Tôi có được cấp số điện thoại Nhật Bản không?','faq.6.a':'CALL SIM có số điện thoại Nhật Bản. DATA SIM không cung cấp số dùng cho gọi thoại.','faq.7.q':'Tôi có thể giữ số điện thoại hiện tại không?','faq.7.a':'CALL SIM hỗ trợ chuyển mạng giữ số (MNP). Vui lòng xem trang đăng ký vì có thông tin bắt buộc và thời hạn áp dụng.','faq.8.q':'Điều gì xảy ra khi dùng hết dữ liệu?','faq.8.a':'Tốc độ sẽ bị giới hạn tối đa 128kbps. Các gói đủ điều kiện có thể mua thêm 1GB với giá 880 yên.','faq.9.q':'Có thời hạn sử dụng tối thiểu hoặc phí hủy không?','faq.9.a':'Không có thời hạn sử dụng tối thiểu. Trang chính thức hiện giới thiệu chương trình miễn phí thủ tục hủy. Hãy xác nhận khi đăng ký xem đây có phải điều kiện lâu dài hay không.','faq.10.q':'Khi nào SIM được giao?','faq.10.a':'Dịch vụ thông báo có thể gửi hàng trong ngày nếu thanh toán và xét duyệt hoàn tất trước 14:00. Thời gian thay đổi tùy khu vực, tồn kho và tình trạng xét duyệt.','faq.11.q':'Làm sao kiểm tra thiết bị tương thích?','faq.11.a':'Hãy kiểm tra tình trạng khóa SIM, băng tần mạng DOCOMO và khả năng hỗ trợ eSIM với nhà sản xuất hoặc nơi bán.',
    'footer.sellerPending':'Đơn vị bán hàng và thông tin công ty: đang chờ xác minh trước khi công bố','footer.relationshipPending':'Thông tin này sẽ được hiển thị sau khi xác nhận mối quan hệ với SUMOU sim và quyền đăng tải.','footer.preview':'Trang xem trước trước khi công bố','image.hero':'Một người Nhật và một cư dân quốc tế cùng mỉm cười khi xem điện thoại thông minh','image.payment':'Khách hàng thanh toán bằng điện thoại tại quầy cửa hàng tiện lợi','image.support':'Nhân viên hỗ trợ đeo tai nghe và hướng dẫn khách hàng','image.setup':'Khách hàng kiểm tra SIM vừa được giao','image.overseas':'Du khách kiểm tra điện thoại tại sân bay'
  },
  zh: {
    'meta.description':'SUMOU sim是面向在日外国人的SIM服务，月费880日元起，支持便利店付款、多语言服务、日本全国免费配送，并可在来日前申请。','a11y.skip':'跳转到主要内容','a11y.language':'选择语言',
    'feature.phone.title':'日本电话号码','feature.phone.body':'使用CALL SIM，可获得用于工作和日常生活的日本电话号码。','feature.overseas.title':'可从海外申请','feature.overseas.body':'来日前即可申请，以便抵达日本后尽快开始使用。','feature.payment.title':'多种付款方式','feature.payment.body':'支持便利店付款、信用卡、银行账户自动扣款等方式。','feature.support.title':'多语言支持','feature.support.body':'主要提供日语、英语、中文和越南语支持。','feature.delivery.title':'日本全国免费配送','feature.delivery.body':'实体SIM卡在日本国内免费配送。','feature.5g.title':'支持5G','feature.5g.body':'使用兼容设备时，开通后可免费切换至5G。',
    'problem.1':'日语合同难以理解','problem.2':'没有信用卡','problem.3':'不知道哪种方案适合自己','problem.4':'需要日本电话号码','problem.5':'不清楚身份验证流程','problem.6':'希望来日前做好准备','problem.answer':'使用SUMOU sim，可清楚了解必要信息并在线申请。',
    'reasons.title':'选择SUMOU sim的理由','reasons.lead':'从申请到开通，将所需信息清楚地呈现给您。','reasons.payment.title':'付款方式由您选择','reasons.payment.body':'即使没有信用卡，也可选择便利店付款、银行账户自动扣款等方式。','reasons.support.title':'多语言服务','reasons.support.body':'主要提供日语、英语、中文和越南语支持。','reasons.setup.title':'按所选方式领取并开始使用','reasons.setup.body':'可根据选择通过配送、机场领取或邮件说明来接收服务。',
    'plan.summary.call':'包含电话号码、语音通话、SMS和数据的方案','plan.summary.data':'以数据和SMS为主的方案','plan.perMonth':'/月','plan.taxIncluded':'含税','plan.call.features':'电话号码、语音通话、SMS和数据','plan.data.features':'数据和SMS','plan.call-light.name':'轻量','plan.call-light.data':'1GB','plan.call-basic.name':'基础','plan.call-basic.data':'3GB','plan.call-standard.name':'标准','plan.call-standard.data':'20GB','plan.call-max.name':'SUMOU MAX','plan.call-max.data':'最近3天内10GB','plan.data-basic.name':'基础','plan.data-basic.data':'3GB','plan.data-standard.name':'标准','plan.data-standard.data':'20GB','plan.data-max.name':'SUMOU MAX','plan.data-max.data':'最近3天内10GB',
    'note.pricing':'显示价格均含税。首次需支付一次性合同事务手续费3,300日元。通话、发送SMS、追加数据等另行收费。价格和活动可能变更，请在申请页面确认最新条件。','note.maxPlan':'SUMOU MAX不适用于数据结转和追加流量购买。','note.speed':'所示速度为技术规格上的最大值。实际速度会因地点、时段、设备、网络拥堵等因素而变化。','note.identity':'身份验证方式因申请类别和领取方式而异。请按照申请页面显示的最新说明办理。','note.device':'使用前请确认设备支持的频段、SIM锁状态和eSIM兼容性。','note.publication':'价格和条件可能变更，请在申请页面确认最新信息。',
    'common.sourceDate':'信息确认日期：','common.yes':'有','common.no':'无','common.free':'免费',
    'comparison.title':'CALL SIM与DATA SIM比较','comparison.caption':'CALL SIM与DATA SIM功能比较','comparison.item':'项目','comparison.data':'移动数据','comparison.phoneNumber':'日本电话号码','comparison.voice':'语音通话','comparison.recommended':'适合用途','comparison.callFor':'工作、日常生活和各种手续','comparison.dataFor':'仅上网和备用设备',
    'network.title':'网络、速度、通话与SMS','network.lead':'开始使用前需要了解的主要网络条件和额外费用。','network.dataTitle':'数据通信','network.carrierLabel':'网络','network.carrier':'NTT DOCOMO网络','network.standardLabel':'制式','network.standards':'4G/LTE；兼容设备支持5G','network.speedLabel':'参考最高速度','network.referenceMaxSpeed':'LTE尽力而为：下行最高375Mbps','network.limitLabel':'超出流量后','network.afterAllowance':'最高128kbps','network.callTitle':'通话','network.domesticCallLabel':'日本国内拨出','network.domesticCall':'22日元 / 30秒','network.incomingLabel':'日本国内接听','network.internationalLabel':'国际电话','network.unavailable':'不可使用','network.smsTitle':'SMS与追加数据','network.smsReceiveLabel':'接收SMS','network.smsDomesticLabel':'发送日本国内SMS','network.smsDomestic':'3.3日元 / 条','network.smsInternationalLabel':'发送国际SMS','network.smsInternational':'110日元 / 条','network.dataAddOnLabel':'追加数据','network.dataAddOn':'1GB 880日元',
    'payment.title':'没有信用卡也可以申请。','payment.convenience':'便利店付款','payment.credit':'信用卡','payment.bank':'银行账户自动扣款','payment.cod':'货到付款','payment.codNote':'仅限在日本国内申请CALL SIM时的初始费用','payment.note':'付款日期和解约办理期限因付款方式而异。详情请查看申请页面和使用条款。',
    'identity.title':'请确认身份验证方式。','identity.domestic.title':'从日本国内申请CALL SIM','identity.domestic.body':'在线申请后，可能需要在Seven Bank ATM使用在留卡验证身份，或在配送时完成身份验证。请按照所选申请方式的说明办理。','identity.overseas.title':'从海外申请CALL SIM','identity.overseas.body':'使用护照申请，并在羽田机场或成田机场领取实体SIM卡或eSIM激活信息。','identity.data.body':'申请时上传护照或在留卡的图片。',
    'steps.1.title':'选择方案','steps.1.body':'选择CALL SIM或DATA SIM以及流量。','steps.2.title':'在线申请','steps.2.body':'在合作方申请页面填写所需信息。','steps.3.title':'付款并验证身份','steps.3.body':'按照说明支付初始费用并完成身份验证。','steps.4.title':'领取SIM或eSIM','steps.4.body':'根据选择，通过配送、机场领取或邮件说明接收。','steps.5.title':'完成设置并开始使用','steps.5.body':'设置APN或eSIM后即可开始使用。',
    'overseas.body':'可从海外申请，并在抵达日本后于机场领取实体SIM或eSIM说明。根据条件，DATA eSIM的手续可能全部在线完成。','overseas.note':'CALL eSIM依法需要完成身份验证，因此可能无法仅通过邮件完成手续，或需在机场等地点领取文件。','device.title':'兼容设备与eSIM','device.body':'请使用无SIM锁设备、已解锁SIM的设备或兼容DOCOMO网络的设备。选择eSIM时，还需确认设备支持eSIM。','final.body':'选择适合您的方案并在线申请。',
    'faq.1.q':'外国人也可以申请吗？','faq.1.a':'可以。请准备所需的身份验证文件并在线申请。','faq.2.q':'可以从海外申请吗？','faq.2.a':'可以。可从海外申请，并在抵达日本后于机场领取。手续因方案和领取方式而异。','faq.3.q':'需要哪些身份验证文件？','faq.3.a':'在日本国内申请CALL SIM时通常需要在留卡，从海外申请时需要护照。DATA SIM可使用护照或在留卡。','faq.4.q':'没有信用卡也可以申请吗？','faq.4.a':'可以。在日本国内可选择便利店付款、银行账户自动扣款等方式。从海外申请时，初始费用可能需要信用卡。','faq.5.q':'可以使用eSIM吗？','faq.5.a':'可以。请确认设备的eSIM兼容性以及各方案的身份验证和领取条件。','faq.6.q':'可以获得日本电话号码吗？','faq.6.a':'CALL SIM提供日本电话号码。DATA SIM不提供用于语音通话的电话号码。','faq.7.q':'可以保留现在的电话号码吗？','faq.7.a':'CALL SIM支持携号转网（MNP）。由于存在所需信息和期限，请确认申请页面的说明。','faq.8.q':'流量用完后会怎样？','faq.8.a':'速度将限制为最高128kbps。适用方案可按1GB 880日元追加流量。','faq.9.q':'有最低使用期限或解约费吗？','faq.9.a':'没有最低使用期限。官方网站目前介绍了免收解约事务手续费的活动。申请时请确认这是否为长期条件。','faq.10.q':'SIM卡什么时候送达？','faq.10.a':'服务说明称，如在下午2点前完成付款和审核，最快可当天发货。实际时间会因地区、库存和审核情况等而异。','faq.11.q':'如何确认设备是否兼容？','faq.11.a':'请向设备制造商或销售店确认SIM锁状态、DOCOMO网络频段和eSIM兼容性。',
    'footer.sellerPending':'销售主体及公司信息：发布前确认中','footer.relationshipPending':'将在确认与SUMOU sim的合同关系及内容发布许可后显示。','footer.preview':'发布前预览页面','image.hero':'一名日本人与一名外国居民一边看智能手机一边微笑交流','image.payment':'顾客在便利店收银台使用智能手机付款','image.support':'佩戴耳麦的客服人员正在提供帮助','image.setup':'用户正在确认刚收到的SIM卡','image.overseas':'旅客在机场查看智能手机'
  }
};

Object.assign(additions.ja, {
  'a11y.home':'SUMOU sim トップへ','a11y.mainNav':'メインナビゲーション','a11y.mobileNav':'モバイルナビゲーション','a11y.menu':'メニューを開く','a11y.serviceFeatures':'サービスの特徴','a11y.planTabs':'SIMプランを選択','a11y.footerNav':'フッターナビゲーション','payment.title':'クレジットカード\nがなくても\n申し込めます。','section.problems':'日本のSIM選びで、\n困っていませんか？'
});
Object.assign(additions.en, {
  'a11y.home':'SUMOU sim home','a11y.mainNav':'Main navigation','a11y.mobileNav':'Mobile navigation','a11y.menu':'Open menu','a11y.serviceFeatures':'Service highlights','a11y.planTabs':'Choose a SIM plan','a11y.footerNav':'Footer navigation','payment.title':'Apply even without\na credit card.','section.problems':'Having trouble choosing\na SIM in Japan?'
});
Object.assign(additions.vi, {
  'a11y.home':'Trang chủ SUMOU sim','a11y.mainNav':'Điều hướng chính','a11y.mobileNav':'Điều hướng di động','a11y.menu':'Mở menu','a11y.serviceFeatures':'Điểm nổi bật của dịch vụ','a11y.planTabs':'Chọn gói SIM','a11y.footerNav':'Điều hướng chân trang','payment.title':'Không có thẻ tín dụng\nvẫn có thể đăng ký.','section.problems':'Bạn gặp khó khăn khi chọn\nSIM tại Nhật Bản?'
});
Object.assign(additions.zh, {
  'a11y.home':'SUMOU sim首页','a11y.mainNav':'主导航','a11y.mobileNav':'移动端导航','a11y.menu':'打开菜单','a11y.serviceFeatures':'服务特点','a11y.planTabs':'选择SIM方案','a11y.footerNav':'页脚导航','payment.title':'没有信用卡\n也可以申请。','section.problems':'选择日本SIM卡时\n遇到困难吗？'
});

const locales = {};
for (const locale of ['ja', 'en', 'vi', 'zh']) {
  const file = path.join(root, 'locales', `${locale}.json`);
  const current = JSON.parse(fs.readFileSync(file, 'utf8'));
  delete current['translation.starterNotice'];
  const merged = { ...current, ...additions[locale] };
  const ordered = Object.fromEntries(Object.entries(merged).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(file, `${JSON.stringify(ordered, null, 2)}\n`);
  locales[locale] = ordered;
}

const referenceKeys = Object.keys(locales.ja);
for (const locale of ['en', 'vi', 'zh']) {
  const missing = referenceKeys.filter((key) => !(key in locales[locale]));
  const extra = Object.keys(locales[locale]).filter((key) => !(key in locales.ja));
  if (missing.length || extra.length) {
    throw new Error(`${locale}: missing=${missing.join(',')} extra=${extra.join(',')}`);
  }
}

for (const locale of ['en', 'vi']) {
  const contaminated = Object.entries(locales[locale]).filter(([, value]) => /[ぁ-んァ-ン]/u.test(value));
  if (contaminated.length) throw new Error(`${locale}: Japanese text remains in ${contaminated.map(([key]) => key).join(',')}`);
}

const bundle = `/* Generated from locales/*.json by scripts/complete-locales.mjs. */\nwindow.SUMOU_LOCALES = Object.freeze(${JSON.stringify(locales, null, 2)});\n`;
fs.writeFileSync(path.join(root, 'locales', 'locales.js'), bundle);
console.log(`Generated ${Object.keys(locales).length} locales with ${referenceKeys.length} keys each.`);
